# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='deethon',
    version='0.3.3',
    description='Python3 library to easily download music from Deezer',
    python_requires='==3.*,>=3.8.0',
    project_urls={"repository": "https://github.com/deethon/deethon"},
    author='Aykut Yilmaz',
    author_email='aykuxt@gmail.com',
    license='GPL-3.0-or-later',
    classifiers=[
        'Development Status :: 3 - Alpha', 'Operating System :: OS Independent'
    ],
    packages=['deethon'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'mutagen==1.*,>=1.44.0', 'pycryptodome==3.*,>=3.9.7',
        'requests==2.*,>=2.23.0'
    ],
    extras_require={
        "docs": [
            "mkdocs==1.*,>=1.1.2", "mkdocs-material==5.*,>=5.2.2",
            "mkdocstrings==0.*,>=0.11.2"
        ]
    },
)
